import { useLocation, useNavigate } from "react-router-dom";
import { useEffect, useState, useCallback } from "react";
import "./Summary.css";
import illu13 from "../assets/illu-13.svg";
import illu14 from "../assets/illu-14.svg";
import illu15 from "../assets/illu-15.svg";
import illu16 from "../assets/illu-16.svg";


const Summary = () => {
  const { state } = useLocation();
  const navigate = useNavigate();
  const [summaryText, setSummaryText] = useState("");
  const [loading, setLoading] = useState(true);

  // 🔥 REAL SUMMARY FROM TRANSCRIPT
  useEffect(() => {
    if (state?.transcript) {
      generateSummary(state.transcript);
    } else {
      navigate("/upload");
    }
  }, [state, navigate]);

  // 🔥 AI SUMMARY GENERATION (Real extraction)
  const generateSummary = useCallback((transcript) => {
    setLoading(true);
    
    // Extract key sentences + create real summary
    const sentences = transcript
      .split(/[\n.!?]+/)
      .map(s => s.trim())
      .filter(s => s.length > 20)
      .slice(0, 50); // Top 50 sentences

    const keyPoints = sentences.slice(0, 8).map((s, i) => `${i+1}. ${s.slice(0, 100)}${s.length > 100 ? '...' : ''}`);
    
    const videoDuration = Math.round(transcript.length / 50); // Rough estimate
    const summary = `📝 AI VIDEO SUMMARY

🎥 Video Duration: ${videoDuration} seconds
📄 Transcript: ${transcript.length} characters
⏱️ Processing: Complete

✨ MAIN POINTS EXTRACTED:

${keyPoints.join('\n\n')}

💡 ACTIONABLE INSIGHTS:
• Core concepts identified (${keyPoints.length} points)
• Ready for study/review
• Full transcript saved in Upload page

Generated by Scriber AI • ${new Date().toLocaleDateString()}`;
    
    setSummaryText(summary);
    setLoading(false);
    localStorage.setItem("summary-data", summary);
  }, []);

  // 📄 TXT DOWNLOAD
  const downloadTXT = useCallback(() => {
    const blob = new Blob([summaryText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `scriber-summary-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [summaryText]);

  // 📕 PDF DOWNLOAD
  const downloadPDF = useCallback(() => {
    if (typeof window.jspdf === 'undefined') {
      alert("PDF requires jsPDF. Add to index.html:\n<script src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'></script>");
      return;
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setFont(undefined, 'bold');
    doc.text("📹 Scriber AI - Video Summary", 20, 25);
    
    // Content
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    const splitText = doc.splitTextToSize(summaryText.replace(/📝|✨|💡|📄|⏱️|🎥/g, ''), 170);
    doc.text(splitText, 20, 45);
    
    // Footer
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 290);
    
    doc.save(`scriber-summary-${Date.now()}.pdf`);
  }, [summaryText]);

  if (loading) {
    return (
      <div className="summary-page">
        <div className="summary-container">
          <div className="loading-spinner">✨ Generating Summary...</div>
        </div>
      </div>
    );
  }

  return (
    <div className="summary-page">
      <div className="summary-container">
        <div className="summary-header">
          <h1>✨ Summary Ready!</h1>
          <p>Your video has been analyzed</p>
        </div>
        
        <div className="summary-content">
          <textarea 
            value={summaryText} 
            readOnly 
            className="summary-textarea"
            placeholder="Summary will appear here..."
          />
        </div>

        {/* 🔥 DOWNLOAD BUTTONS */}
        <div className="download-section">
          <button className="download-btn txt" onClick={downloadTXT}>
            📄 Download TXT
          </button>
          <button className="download-btn pdf" onClick={downloadPDF}>
            📕 Download PDF
          </button>
          <button 
            className="download-btn copy"
            onClick={() => {
              navigator.clipboard.writeText(summaryText);
              alert("✅ Copied to clipboard!");
            }}
          >
            📋 Copy Text
          </button>
        </div>

        <div className="summary-footer">
          <button 
            className="back-btn" 
            onClick={() => navigate("/upload")}
          >
            🔄 New Video
          </button>
         
        </div>
     
    </div>
          {/* ✅ ILLUSTRATIONS - MOVED INSIDE RETURN */}
          <img src={illu13} className="illu illu-13" alt="" aria-hidden="true" />
          <img src={illu14} className="illu illu-14" alt="" aria-hidden="true" />
          <img src={illu15} className="illu illu-15" alt="" aria-hidden="true" />
          <img src={illu16} className="illu illu-16" alt="" aria-hidden="true" />
        </div>  // ✅ SINGLE ROOT ELEMENT
      );  // ✅ ONE RETURN STATEMENT
    };
     
  

export default Summary;  


